name    'domeus-zookeeper2'
version '0.1.0'
source ''
author 'Francesco Salbaroli'
license 'Apache License v2.0'
summary ''
description ''
project_page ''

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'tguentne-java', '0.0.1'
dependency 'adrien-alternatives', '0.1.0'
dependency 'puppetlabs-stdlib', '3.2.0'
