define es::docker::collectd::curl_json::dsesd () {
  collectd::plugin::curl_json {
  "es_nodes_stats_${name}":
    url      => "http://${name}:9200/_nodes/${esnodes['dsesd'][$name]}/stats",
    instance => "es-nodes-stats-${name}",
    keys     => {
      'nodes/*/indices/docs/count' => {'type' => 'gauge'},
      'nodes/*/indices/docs/deleted' => {'type' => 'gauge'},
      'nodes/*/indices/store/size_in_bytes' => {'type' => 'gauge'},
      'nodes/*/indices/indexing/index_total' => {'type' => 'gauge'},
      'nodes/*/indices/indexing/index_failed' => {'type' => 'gauge'},
      'nodes/*/indices/indexing/index_time_in_millis' => {'type' => 'gauge'},
      'nodes/*/indices/get/total' => {'type' => 'gauge'},
      'nodes/*/indices/get/time_in_millis' => {'type' => 'gauge'},
      'nodes/*/indices/search/query_total' => {'type' => 'gauge'},
      'nodes/*/indices/search/query_time_in_millis' => {'type' => 'gauge'},
      'nodes/*/indices/search/fetch_total' => {'type' => 'gauge'},
      'nodes/*/indices/search/fetch_time_in_millis' => {'type' => 'gauge'},
      'nodes/*/indices/search/scroll_total' => {'type' => 'gauge'},
      'nodes/*/indices/search/scroll_time_in_millis' => {'type' => 'gauge'},
      'nodes/*/indices/merges/total' => {'type' => 'gauge'},
      'nodes/*/indices/merges/total_time_in_millis' => {'type' => 'gauge'},
      'nodes/*/indices/merges/total_docs' => {'type' => 'gauge'},
      'nodes/*/indices/merges/total_size_in_bytes' => {'type' => 'gauge'},
      'nodes/*/indices/query_cache/memory_size_in_bytes' => {'type' => 'gauge'},
      'nodes/*/indices/query_cache/total_count' => {'type' => 'gauge'},
      'nodes/*/indices/query_cache/hit_count' => {'type' => 'gauge'},
      'nodes/*/indices/query_cache/miss_count' => {'type' => 'gauge'},
      'nodes/*/indices/query_cache/evictions' => {'type' => 'gauge'},
      'nodes/*/process/open_file_descriptors' => {'type' => 'gauge'},
      'nodes/*/process/max_file_descriptors' => {'type' => 'gauge'},
      'nodes/*/process/cpu/total_in_millis' => {'type' => 'gauge'},
      'nodes/*/process/mem/total_virtual_in_bytes' => {'type' => 'gauge'},
      'nodes/*/jvm/uptime_in_millis' => {'type' => 'gauge'},
      'nodes/*/jvm/mem/heap_max_in_bytes' => {'type' => 'gauge'},
      'nodes/*/jvm/mem/heap_used_in_bytes' => {'type' => 'gauge'},
      'nodes/*/jvm/mem/non_heap_used_in_bytes' => {'type' => 'gauge'},
      'nodes/*/jvm/threads/count' => {'type' => 'gauge'},
      'nodes/*/jvm/threads/peak_count' => {'type' => 'gauge'},
      'nodes/*/thread_pool/generic/active' => {'type' => 'gauge'},
      'nodes/*/thread_pool/generic/queue' => {'type' => 'gauge'},
      'nodes/*/thread_pool/generic/threads' => {'type' => 'gauge'},
      'nodes/*/thread_pool/search/active' => {'type' => 'gauge'},
      'nodes/*/thread_pool/search/queue' => {'type' => 'gauge'},
      'nodes/*/thread_pool/search/threads' => {'type' => 'gauge'},
    }
  }
}