---
hadoop::master_cluster_dfs: 'dsstg1cluster'
hadoop::master_cluster_mr: 'dsstg1cluster_mr'
hadoop::config::mapreduce_map_java_opts: '-Xmx2536m'
hadoop::config::mapreduce_map_memory_mb: '4096'
hadoop::config::mapreduce_reduce_java_opts: '-Xmx4096m'
hadoop::config::mapreduce_reduce_memory_mb: '8192'
hadoop::config::master_historyserver: 'os13dshdm02.muc.domeus.com'
hadoop::config::master_jobtracker1: 'os13dshdm01.muc.domeus.com'
hadoop::config::master_jobtracker1_alias: 'dsstg1nn1'
hadoop::config::master_jobtracker2: 'os13dshdm02.muc.domeus.com'
hadoop::config::master_jobtracker2_alias: 'dsstg1nn2'
hadoop::config::master_resourcemanager: 'os13dshdm01.muc.domeus.com'
hadoop::config::namenode_heap_mb: '8192'
hadoop::config::yarn_app_mapreduce_am_resource_mb: '2048'
hadoop::config::yarn_app_mapreduce_am_staging_dir: '/user/'
hadoop::config::yarn_log_aggregation_enable: 'true'
hadoop::config::yarn_nodemanager_remote_app_log_dir: '/var/log/hadoop-yarn/apps'
hadoop::config::yarn_nodemanager_resource_cpu_vcores: '16'
hadoop::config::yarn_resourcemanager_zk_state_store_parent_path: '/rmstore'
hadoop::config::yarn_scheduler_capacity_maximum_applications: '400'
hadoop::config::yarn_scheduler_capacity_root_queues: 'default,snapshots,elastic,etl_jobs'
hadoop::config::yarn_scheduler_capacity_queues_settings:
  default:
    queue_name: 'default'
    root_queue_name: 'root.default'
    capacity: '18.0'
    maximum_capacity: '100'
    maximum_applications: '150'
    state: 'RUNNING'
    acl_submit_applications: 'hdfs,hbase,yarn'
    acl_administer_queue: 'hdfs,hbase,yarn'
    user_limit_factor: '2.0'
  elastic:
    queue_name: 'elastic'
    root_queue_name: 'root.elastic'
    capacity: '2.0'
    maximum_capacity: '30'
    maximum_applications: ''
    state: 'RUNNING'
    acl_submit_applications: 'hdfs,hbase,yarn'
    acl_administer_queue: 'hdfs,hbase,yarn'
    user_limit_factor: '15.0'
  snapshots:
    queue_name: 'snapshots'
    root_queue_name: 'root.snapshots'
    capacity: '20.0'
    maximum_capacity: '100'
    maximum_applications: '50'
    state: 'RUNNING'
    acl_submit_applications: 'snapshots,hdfs'
    acl_administer_queue: 'snapshots,hdfs'
    user_limit_factor: '2.0'
  etl_jobs:
    queue_name: 'etl_jobs'
    root_queue_name: 'root.etl_jobs'
    capacity: '60.0'
    maximum_capacity: '90'
    maximum_applications: ''
    state: 'RUNNING'
    acl_submit_applications: 'snapshots,hdfs'
    acl_administer_queue: 'snapshots,hdfs'
    user_limit_factor: '2.0'
