---
lookup_options:
  hadoop::config::configuration_files:
    merge: first
hadoop::data_mounts:
  - '/DATA1'
  - '/DATA2'
hadoop::config::configuration_files:
  base:
    '/etc/hadoop/conf-puppet/hadoop-metrics.properties': {}
    '/etc/hadoop/conf-puppet/hadoop-metrics2.properties': {}
    '/etc/hadoop/conf-puppet/log4j.properties': {}
    '/etc/hadoop/conf-puppet/hadoop-env.sh': {}
    '/etc/hadoop/conf-puppet/core-site.xml': {}
  exec:
    '/etc/hadoop/conf-puppet/topology.py':
      mode: '0755'
  hdfs:
    '/etc/hadoop/conf-puppet/hdfs-site.xml': {}
    '/etc/hadoop/conf-puppet/masters': {}
    '/etc/hadoop/conf-puppet/slaves': {}
  mapred:
    '/etc/hadoop/conf-puppet/mapred-env.sh': {}
    '/etc/hadoop/conf-puppet/mapred-site.xml': {}
    '/etc/hadoop/conf-puppet/fair-scheduler.xml': {}
  yarn:
    '/etc/hadoop/conf-puppet/yarn-env.sh': {}
    '/etc/hadoop/conf-puppet/yarn-site.xml': {}
    '/etc/hadoop/conf-puppet/capacity-scheduler.xml': {}
hadoop::master_cluster_dfs: 'dsstg1cluster'
hadoop::config::master_namenode1: 'os13dshdm01.muc.domeus.com'
hadoop::config::master_namenode1_alias: 'dsstg1hbnn1'
hadoop::config::master_namenode2: 'os13dshdm02.muc.domeus.com'
hadoop::config::master_namenode2_alias: 'dsstg1hbnn2'
hadoop::config::namenode_heap_mb: '8192'
hadoop::config::topology:
  - '192.168.139.92,/rack0'
  - '192.168.139.93,/rack0'
  - '192.168.139.94,/rack0'
  - '192.168.139.95,/rack1'
  - '192.168.139.96,/rack1'
  - '192.168.139.97,/rack1'
hadoop::config::dfs_datanode_failed_volumes_tolerated: 1

hadoop::master_cluster_dfs: 'dsstg1cluster'
hadoop::master_cluster_mr: 'dsstg1cluster_mr'
hadoop::config::mapreduce_map_java_opts: '-Xmx2536m'
hadoop::config::mapreduce_map_memory_mb: '4096'
hadoop::config::mapreduce_reduce_java_opts: '-Xmx4096m'
hadoop::config::mapreduce_reduce_memory_mb: '4096'
hadoop::config::master_historyserver: 'os13dshdm02.muc.domeus.com'
hadoop::config::master_jobtracker1: 'os13dshdm01.muc.domeus.com'
hadoop::config::master_jobtracker1_alias: 'dsstg1nn1'
hadoop::config::master_jobtracker2: 'os13dshdm02.muc.domeus.com'
hadoop::config::master_jobtracker2_alias: 'dsstg1nn2'
hadoop::config::master_resourcemanager: 'os13dshdm01.muc.domeus.com'
hadoop::config::namenode_heap_mb: '8192'
hadoop::config::yarn_app_mapreduce_am_resource_mb: '2048'
hadoop::config::yarn_app_mapreduce_am_staging_dir: '/user/'
hadoop::config::yarn_log_aggregation_enable: 'true'
hadoop::config::yarn_nodemanager_remote_app_log_dir: '/var/log/hadoop-yarn/apps'
hadoop::config::yarn_nodemanager_resource_cpu_vcores: '16'
hadoop::config::yarn_resourcemanager_zk_state_store_parent_path: '/rmstore'
hadoop::config::yarn_scheduler_capacity_maximum_applications: '400'
hadoop::config::yarn_scheduler_capacity_root_queues: 'default,snapshots,elastic,etl_jobs'
hadoop::config::yarn_scheduler_capacity_queues_settings:
  default:
    queue_name: 'default'
    root_queue_name: 'root.default'
    capacity: '18.0'
    maximum_capacity: '100'
    maximum_applications: '150'
    state: 'RUNNING'
    acl_submit_applications: 'hdfs,hbase,yarn'
    acl_administer_queue: 'hdfs,hbase,yarn'
    user_limit_factor: '2.0'
  elastic:
    queue_name: 'elastic'
    root_queue_name: 'root.elastic'
    capacity: '2.0'
    maximum_capacity: '30'
    maximum_applications: ''
    state: 'RUNNING'
    acl_submit_applications: 'hdfs,hbase,yarn'
    acl_administer_queue: 'hdfs,hbase,yarn'
    user_limit_factor: '15.0'
  snapshots:
    queue_name: 'snapshots'
    root_queue_name: 'root.snapshots'
    capacity: '20.0'
    maximum_capacity: '100'
    maximum_applications: '50'
    state: 'RUNNING'
    acl_submit_applications: 'snapshots,hdfs'
    acl_administer_queue: 'snapshots,hdfs'
    user_limit_factor: '2.0'
  etl_jobs:
    queue_name: 'etl_jobs'
    root_queue_name: 'root.etl_jobs'
    capacity: '60.0'
    maximum_capacity: '90'
    maximum_applications: ''
    state: 'RUNNING'
    acl_submit_applications: 'snapshots,hdfs'
    acl_administer_queue: 'snapshots,hdfs'
    user_limit_factor: '2.0'

hbase::config::master_cluster_dfs: 'dsstg1cluster'
hbase::config::zookeeper_znode_parent: '/hbase'
